Repository Techit7-11/goohaeyou, pull requests merged in 2024-03, with the labels that each got.

#112 Feature/review
  build.gradle
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/member/me/+page.svelte
  front/src/routes/member/review/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/mapper/ReviewMapper.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/controller/ReviewController.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/dto/ApplicantReviewDto.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/entity/Review.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/repository/ReviewRepository.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/service/ReviewService.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/service/ReviewServiceImpl.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
Labels: BE, FE, feature, UI

#115 Feature/payment and wage 급여 기능, 토스페이먼츠 연동, 결제기능 추가
  front/package-lock.json
  front/package.json
  front/src/lib/global.d.ts
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/+page.svelte
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/applications/modify/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/list/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/payment/fail/+page.svelte
  front/src/routes/payment/pay/[id]/[deposit]/+page.svelte
  front/src/routes/payment/success/+page.svelte
  front/static/tosspayments.jpg
  src/main/java/com/ll/gooHaeYu/domain/application/application/dto/ApplicationDto.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/DepositStatus.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/service/ApplicationService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/EmployService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/controller/InterestController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/AbstractJobPostDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostForm.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/JobPostDetail.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/Wage.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/type/WageType.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/repository/WageRepository.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/service/JobPostService.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/entity/Member.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/entity/type/Gender.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/service/CashService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/controller/PaymentController.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/cancel/PaymentCancelResDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/fail/PaymentFailDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/request/PaymentReqDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/request/PaymentResDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/PaymentSuccessDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/SuccessCardDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/SuccessEasyPayDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/Payment.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PayType.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PayTypeFee.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PaymentEvent.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PaymentStatus.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/repository/PaymentRepository.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentCancelService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
  src/main/java/com/ll/gooHaeYu/global/config/RestTemplateConfig.java
  src/main/java/com/ll/gooHaeYu/global/config/TossPaymentsConfig.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
  src/main/java/com/ll/gooHaeYu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ll/gooHaeYu/standard/base/util/TossPaymentUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: BE, FE, feature, refactor, UI

#117 Hotfix/front bug #115 PR 충돌 해결
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/applications/modify/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
Labels: bug, UI

#116 Feature/map
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/[id]/Map.svelte
  front/src/routes/maps/+page.svelte
  front/src/routes/maps/Map.svelte
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDto.java
Labels: FE, feature, UI

#120 Feature/payment2 결제기능 리팩토링, 알바완료(수동) 기능 구현
  .github/workflows/deploy-aws.yml
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/payment/pay/[id]/[deposit]/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/dto/ApplicationDto.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/DepositStatus.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/service/ApplicationService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/WorkCompletionController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/WorkCompletionService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/AbstractJobPostDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/request/PaymentReqDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/request/PaymentResDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/PaymentSuccessDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/Payment.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PayStatus.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PayTypeFee.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PaymentStatus.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
  src/main/java/com/ll/gooHaeYu/global/initData/NotProd.java
Labels: BE, FE, feature, refactor

#122 Feature/payment4 캐시로그 기능 추가
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/payment/success/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostForm.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/Wage.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/type/PayBasis.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/type/WageType.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/service/JobPostService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/entity/CashLog.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/entity/type/EventType.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/repository/CashLogRepository.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/service/CashLogService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/PaymentSuccessDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/type/PaymentEvent.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
Labels: BE, feature

#126 Feature/payment5 select 급여 지급 방식 선택 기능 추가
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/payment/pay/[id]/[wages]/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/dto/ApplicationDto.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/DepositStatus.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/WageStatus.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/service/ApplicationService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/WorkCompletionController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/EmployService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/WorkCompletionService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostForm.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/JobPostDetail.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/Wage.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/type/WagePaymentMethod.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/service/JobPostService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/entity/type/EventType.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
Labels: BE, FE, feature, refactor

#129 release: 4차 배포
  .github/workflows/deploy-aws.yml
  src/main/resources/application-prod.yml
Labels: Infra

#130 Feature/front refactoring3 프론트 디자인 수정
  .github/workflows/deploy-aws.yml
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/payment/success/+page.svelte
Labels: UI

#132 Feature/job-start-date 일 시작일
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/EmployService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/AbstractJobPostDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostForm.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/JobPost.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/service/JobPostService.java
Labels: BE, FE, feature

#133 Feature/workTime-workDays
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/EmployService.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostDetailDto.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/dto/JobPostForm.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/Wage.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/entity/type/PayBasis.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/service/JobPostService.java
Labels: BE, FE, feature

#136 Feature/cancel-request 알바비 결제 취소 기능
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/payment/cancel/[id]/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/Application.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/WageStatus.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/EmployService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/service/CashLogService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/controller/PaymentController.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/PaymentDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/cancel/PaymentCancelResDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/repository/PaymentRepository.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentCancelService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentInfoService.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
  src/main/java/com/ll/gooHaeYu/standard/base/util/TossPaymentUtil.java
Labels: BE, FE, feature, refactor

#137 Feature/individual-payment-cancel 지급 방식이 개인 지급인 알바 취소 처리 구현, 캐시로그 리팩토링
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/payment/success/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/entity/type/WageStatus.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/WorkCompletionController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/service/WorkCompletionService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/eventListener/CashLogEventListener.java
  src/main/java/com/ll/gooHaeYu/domain/payment/cashLog/service/CashLogService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentCalculationService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentCancelService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
Labels: BE, FE, feature, refactor

#138 Feature/api-response ApiResponse 구현 및 적용
  .github/workflows/deploy-aws.yml
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/[id]/write/+page.svelte
  front/src/routes/applications/detail/[id]/+page.svelte
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/applications/modify/[id]/+page.svelte
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/member/join/+page.svelte
  front/src/routes/member/login/+page.svelte
  front/src/routes/member/review/+page.svelte
  front/src/routes/member/social/modify/+page.svelte
  front/src/routes/payment/cancel/[id]/+page.svelte
  front/src/routes/payment/fail/+page.svelte
  front/src/routes/payment/success/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/controller/ApplicationController.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/service/ApplicationService.java
  src/main/java/com/ll/gooHaeYu/domain/chat/message/controller/MessageController.java
  src/main/java/com/ll/gooHaeYu/domain/chat/room/controller/RoomController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/comment/controller/CommentController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/EmployController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/WorkCompletionController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/controller/InterestController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/controller/JobPostController.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/controller/ReviewController.java
  src/main/java/com/ll/gooHaeYu/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/controller/PaymentController.java
  src/main/java/com/ll/gooHaeYu/global/exception/CustomHttpStatus.java
  src/main/java/com/ll/gooHaeYu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ll/gooHaeYu/global/exception/type/ApiResultType.java
  src/main/java/com/ll/gooHaeYu/global/rsData/ApiResponse.java
  src/main/java/com/ll/gooHaeYu/global/rsData/RsData.java
Labels: BE, refactor

#139 Feature/refactoring-5 리팩토링
  .github/workflows/deploy-aws.yml
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/payment/success/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/dto/success/PaymentSuccessDto.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentCancelService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentInfoService.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
  src/main/java/com/ll/gooHaeYu/global/config/TossPaymentsConfig.java
  src/main/java/com/ll/gooHaeYu/standard/base/util/TossPaymentUtil.java
  src/main/resources/application-secret.yml.default
  src/main/resources/application.yml
  src/test/java/com/ll/gooHaeYu/GooHaeYuApplicationTests.java
Labels: BE, refactor

#145 Feature/test-application1
  src/main/java/com/ll/gooHaeYu/domain/application/application/dto/ApplicationForm.java
  src/main/java/com/ll/gooHaeYu/domain/application/application/service/ApplicationService.java
  src/test/java/com/ll/gooHaeYu/controller/application/ApplicationControllerIntegrationTest.java
  src/test/java/com/ll/utils/JoinFormBuilder.java
  src/test/java/com/ll/utils/builder/JobPostWriteFormBuilder.java
  src/test/java/com/ll/utils/builder/JoinFormBuilder.java
Labels: test

#146 Feature/test mypage
  src/test/java/com/ll/gooHaeYu/controller/jopPost/MypageControllerIntegrationTest.java
Labels: test

#147 Feature/optimistic-lock 리팩토링 및 동시성 제어 적용
  README.md
  fly.toml
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/job-post/[id]/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/application/application/controller/ApplicationController.java
  src/main/java/com/ll/gooHaeYu/domain/chat/message/controller/MessageController.java
  src/main/java/com/ll/gooHaeYu/domain/chat/room/controller/RoomController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/comment/controller/CommentController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/EmployController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/employ/controller/WorkCompletionController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/controller/InterestController.java
  src/main/java/com/ll/gooHaeYu/domain/jobPost/jobPost/controller/JobPostController.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/controller/MypageController.java
  src/main/java/com/ll/gooHaeYu/domain/member/review/controller/ReviewController.java
  src/main/java/com/ll/gooHaeYu/domain/notification/controller/NotificationController.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/controller/PaymentController.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/entity/Payment.java
  src/main/java/com/ll/gooHaeYu/domain/payment/payment/service/PaymentService.java
  src/main/java/com/ll/gooHaeYu/global/apiResponse/ApiResponse.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
  src/main/java/com/ll/gooHaeYu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ll/gooHaeYu/global/exception/type/ApiResultType.java
  src/main/java/com/ll/gooHaeYu/global/initData/NotProd.java
  src/main/java/com/ll/gooHaeYu/global/readiness/controller/ReadinessController.java
  src/main/java/com/ll/gooHaeYu/standard/dto/PageDto.java
  src/main/java/com/ll/gooHaeYu/standard/dto/retryOnOptimisticLock/OptimisticLockingRetryAspect.java
  src/main/java/com/ll/gooHaeYu/standard/dto/retryOnOptimisticLock/RetryOnOptimisticLock.java
  src/test/java/com/ll/gooHaeYu/controller/application/ApplicationControllerIntegrationTest.java
  src/test/java/com/ll/gooHaeYu/controller/jobPost/MypageControllerIntegrationTest.java
Labels: BE, feature, refactor, test

#150 Feature/email-authentication 이메일 본인인증 기능 추가
  build.gradle
  front/src/lib/rq/rq.svelte.ts
  front/src/lib/types/api/v1/schema.d.ts
  front/src/routes/applications/[id]/write/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/member/join/+page.svelte
  front/src/routes/member/me/+page.svelte
  src/main/java/com/ll/gooHaeYu/domain/member/emailAuth/controller/EmailAuthController.java
  src/main/java/com/ll/gooHaeYu/domain/member/emailAuth/entity/EmailAuth.java
  src/main/java/com/ll/gooHaeYu/domain/member/emailAuth/repository/EmailAuthRepository.java
  src/main/java/com/ll/gooHaeYu/domain/member/emailAuth/service/EmailAuthService.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/dto/JoinForm.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/dto/MemberDto.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/entity/Member.java
  src/main/java/com/ll/gooHaeYu/domain/member/member/service/MemberService.java
  src/main/java/com/ll/gooHaeYu/global/exception/ErrorCode.java
  src/main/java/com/ll/gooHaeYu/global/security/MemberDetails.java
  src/main/resources/application-secret.yml.default
  src/main/resources/application.yml
  src/main/resources/templates/emailTemplate.html
Labels: BE, FE, feature, UI

#152 Feature/email-refactoring 본인인증 오류 수정
  src/main/java/com/ll/gooHaeYu/domain/member/member/service/MemberService.java
Labels: refactor, bug

#154 Hotfix/build3 빌드 문제 해결
  src/main/resources/application-test.yml
Labels: bug, Infra

#156 Feature/front job post refactoring 마이페이지, 공고 상세 페이지 디자인 수정
  front/src/routes/job-post/[id]/+page.svelte
  front/src/routes/member/me/+page.svelte
  front/tailwind.config.js
Labels: UI

#159 Feature/token 배포 서버에 토큰 적용
  .github/workflows/deploy-aws.yml
  .gitignore
Labels: Infra

#161 Hotfix/build4 빌드 문제 해결
  src/main/java/com/ll/gooHaeYu/domain/notification/service/NotificationService.java
Labels: Infra

#163 Feature/front 1 프론트 디자인 수정
  .gitignore
  front/src/routes/job-post/modify/[id]/+page.svelte
  front/src/routes/job-post/write/+page.svelte
  front/src/routes/member/login/+page.svelte
  front/tailwind.config.js
Labels: UI

#164 Hotfix/modify script 배포 yml 파일 수정
  .github/workflows/deploy-aws.yml
Labels: Infra

#171 Hotfix/front deploy 프론트 배포
  front/src/routes/payment/success/+page.svelte
Labels: Infra

#172 Feature/front 7 프론트 디자인 수정
  front/src/routes/+page.svelte
  front/src/routes/applications/list/[id]/+page.svelte
  front/src/routes/member/me/+page.svelte
Labels: UI
